[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
upload_port = COM7
monitor_port = COM7
monitor_speed = 115200
upload_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -DTELEM_ACTIVE_SCHEMA_ID=TELEM_SCHEMA_ID_RELEASE_0_03_CANDIDATE
