[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
upload_port = COM10
monitor_port = COM10
monitor_speed = 115200
build_flags =
    -DENABLE_MIRROR=1
    -I../ESP_AIR/src
lib_deps =
    adafruit/Adafruit BMP280 Library@^2.6.8
